"""Markdown export for analysis results."""
from app.schemas import AnalysisResult


def to_markdown(
    analysis: AnalysisResult,
    cv_name: str = "Candidate",
    job_title: str = "AI/ML Engineer",
) -> str:
    lines: list[str] = [
        f"# Career Gap Analysis — {cv_name}",
        f"**Target Role:** {job_title}",
        "",
        "---",
        "",
        "## Fit Score",
        "",
        f"**Overall Fit Score: {analysis.fit_score:.1f} / 100**",
        "",
    ]

    if analysis.fit_assessment:
        lines += [analysis.fit_assessment, ""]

    if analysis.explanation:
        lines += [f"> {analysis.explanation}", ""]

    # Category breakdown
    if analysis.category_scores:
        lines += ["## Category Breakdown", ""]
        lines.append("| Category | Score |")
        lines.append("|---|---|")
        for cat, score in sorted(analysis.category_scores.items(), key=lambda x: -x[1]):
            bar = _score_bar(score)
            lines.append(f"| {cat} | {bar} {score:.0f}% |")
        lines.append("")

    # Strong matches
    if analysis.strong_matches:
        lines += ["## Strong Matches", ""]
        for m in analysis.strong_matches:
            lines.append(f"- **{m.skill}** *({m.category})*")
            if m.evidence:
                lines.append(f"  > {m.evidence[:100]}")
        lines.append("")

    # Partial matches
    if analysis.partial_matches:
        lines += ["## Partial Matches", ""]
        for m in analysis.partial_matches:
            lines.append(
                f"- **{m.skill}** *({m.category})* — similarity: {m.similarity_score:.0%}"
            )
        lines.append("")

    # Missing skills
    if analysis.missing_required_skills:
        lines += ["## Missing Skills", ""]
        for skill in analysis.missing_required_skills:
            lines.append(f"- {skill}")
        lines.append("")

    # Recommendations
    if analysis.recommendations:
        lines += ["## Recommended Projects & Actions", ""]
        for i, rec in enumerate(analysis.recommendations, 1):
            lines.append(f"{i}. {rec}")
        lines.append("")

    # Resume suggestions
    if analysis.resume_suggestions:
        lines += ["## Resume Improvement Suggestions", ""]
        for s in analysis.resume_suggestions:
            lines.append(f"- {s}")
        lines.append("")

    # Learning plan
    plan = analysis.learning_plan
    if any([plan.days_30, plan.days_60, plan.days_90]):
        lines += ["## 30 / 60 / 90 Day Learning Plan", ""]
        if plan.days_30:
            lines += ["### First 30 Days", ""]
            for item in plan.days_30:
                lines.append(f"- {item}")
            lines.append("")
        if plan.days_60:
            lines += ["### Days 31–60", ""]
            for item in plan.days_60:
                lines.append(f"- {item}")
            lines.append("")
        if plan.days_90:
            lines += ["### Days 61–90", ""]
            for item in plan.days_90:
                lines.append(f"- {item}")
            lines.append("")

    lines += [
        "---",
        "*Generated by AI Career Gap Analyzer — for guidance only. "
        "This tool does not replace professional career advice or guarantee hiring outcomes.*",
    ]

    return "\n".join(lines)


def _score_bar(score: float, width: int = 10) -> str:
    filled = round(score / 100 * width)
    return "█" * filled + "░" * (width - filled)
